# Generated by Django 2.2.16 on 2020-12-02 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='is_subscribed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
