# Generated by Django 2.2.16 on 2020-10-24 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='event_staff', to='users.Staff'),
        ),
        migrations.AddField(
            model_name='event',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='event_volunteer', to='users.Volunteer'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='enrollment_event', to='events.Event'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='victim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='enrollment_victim', to='users.Victim'),
        ),
    ]
