# Generated by Django 2.2.16 on 2020-10-25 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20201024_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='public_event_img',
            field=models.ImageField(blank=True, null=True, upload_to='events/images'),
        ),
    ]
