# Generated by Django 2.2.4 on 2020-12-06 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20201103_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_event', to='events.Event'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='is_important',
            field=models.BooleanField(blank=True, default=False, verbose_name='Victim needs urgent attention!!'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_important',
            field=models.BooleanField(blank=True, default=False, verbose_name='Victim needs urgent attention!!'),
        ),
    ]
